language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then pip install pylint; fi
  - pip install ordereddict pyyaml mysqlclient

before_script:
  - if [[ $TRAVIS_TAG == apptuit-v* ]]; then export PACKAGE_VERSION=${TRAVIS_TAG#apptuit-v}; fi
  - echo $TRAVIS_TAG
  - echo $PACKAGE_VERSION

script:
  - python -c "import sys; print('python version:%s' % sys.version);"
  - python -c "import sys; print('python version:%s' % sys.version[0]);"
  - ./pylint-runner.py -s
  - ./tests.py
  - make -C rpm
  - make -C deb


before_deploy:
  - PACKAGE_DATE=$(git log -1 --pretty="format:%ad" $TRAVIS_TAG --date=short);
  - echo $PACKAGE_DATE;
  - sed -e "s/@PACKAGE_DATE@/$PACKAGE_DATE/" -e "s/@PACKAGE_VERSION@/$PACKAGE_VERSION/" -i deb/bintray-descriptor.json;
  - cat deb/bintray-descriptor.json;
  - sed -e "s/@PACKAGE_DATE@/$PACKAGE_DATE/" -e "s/@PACKAGE_VERSION@/$PACKAGE_VERSION/" -i rpm/bintray-descriptor.json;
  - cat rpm/bintray-descriptor.json;

deploy:
  - provider: bintray
    file: "deb/bintray-descriptor.json"
    user: "$BINTRAY_USER"
    key: "$BINTRAY_API_KEY"
    on:
      tags: true
      condition: $PACKAGE_VERSION != "" && $TRAVIS_PYTHON_VERSION == "2.7" && $BINTRAY_API_KEY != ""
  - provider: bintray
    file: "rpm/bintray-descriptor.json"
    user: "$BINTRAY_USER"
    key: "$BINTRAY_API_KEY"
    on:
      tags: true
      condition: $PACKAGE_VERSION != "" && $TRAVIS_PYTHON_VERSION == "2.7" && $BINTRAY_API_KEY != ""